src/mixed.js
I didn't remove from the lib/ dir since I assumed that dir is built as part of the build process.
=> removed `is` from `is must be...` message

src/boolean.js, src/number.js, src/string.js, test/bool.js, test/number.js, test/string.js
Yo, I think this is valuable. The check is not too insane so it might not target IE 6.12beta or some weird version of Safari, but I think it's good enough :D
=> String objects should be considered valid strings.

src/locale.js
Just bumped into this! Not a world changing fix but it proves people are using your software. :D
=> Fixed minor typo in the ojbect.noUnknown error message

src/locale.js
And change number min wording to match max
=> [Fix] string max locale wording

README.md, lib/locale.js, lib/mixed.js, lib/util/createValidation.js, lib/util/set.js, lib/util/validation-error.js, src/mixed.js, src/util/createValidation.js, src/util/validation-error.js, test/mixed.js
As requested in issue Add .label() option #13
=> Added label() options

test/object.js
=> fix test suite

README.md
=> update docs on mixed().default(...) and nulls

src/locale.js, src/string.js, test/string.js
Instead of having to set min and max to specify a precise length for a string this pull request adds a length method to string.
=> Added ability to validate string with exact length.

README.md
Fix custom locale path in `README.md`
=> Fix custom locale path

README.md
Ad described in https://github.com/jquense/yup/issues/15#issuecomment-160146849
=> Fix wrong doc for isValid

src/util/printValue.js
=> Check for Symbol

README.md
Is there anything else that should be removed?
I have only tested these 2 cases personally.
=> Remove outdated statements from README.md

CHANGELOG.md, README.md
=> Update CHANGELOG and README with 0.24 changes.

src/locale.js
Change "Must be at earlier than" -> "Must be earlier than"
=> Fix date validation message

README.md
Hi there,
Love your library
Noticed this typo because there was Portuguese and `yo hablo español señor` (dictionary is similarly spelt in different languages).
Thanks,
Dan
=> Correct spelling of dictionary in Readme.md

README.md
https://github.com/jquense/yup/issues/214
=> imports on ES6 change in README

README.md
=> fix(readme): wrong variable name on Extending Schema Types section

README.md
I was searching for the url validation when I came across this 
it's no big deal but it's better added
=> Add missing colon in README.md

src/number.js, test/number.js
Also adds support hex decimals
Fixes issue #177
=> Fixes issue #177

src/number.js, test/number.js
=> 0 is not positive or negative

README.md, src/mixed.js, src/util/createValidation.js, test/mixed.js
=> #411 Add testsParams to SchemaDescription

README.md
Feel free to ignore, but the sentence wasn't fully baked.
=> Updated README intro to read a little easier

src/mixed.js
Finding usage for #456 have not made you wait for long.
=> fix: do concat in mutation mode

package.json
=> change @babel/runtime version to be a range

src/string.js, test/string.js
=> fix: string.matches() and regex global flag

CHANGELOG.md
=> docs: Warning on locale properties breaking change

src/date.js
See issue https://github.com/jquense/yup/issues/731
=> Fix date strings before 1970 too

src/mixed.js, test/mixed.js
=> Expose blacklist and whitelist values on description

README.md
Fixing the redirect link inside the `README.md` :)
=> docs: fix not required link

src/locale.ts, src/setLocale.ts
The setLocale file was changed to .ts and the LocaleObject interface was created in locale.ts
Close #1321.
=> feat: add types to setLocale

src/schema.ts, test/string.js
=> fix: oneOf, notOneOf swallowing multiple errors

README.md, src/schema.ts, src/util/ReferenceSet.ts, test/mixed.js
=> Add resolved to params

README.md
Show an example of [a function message parameter](https://github.com/jquense/yup/issues/640#issuecomment-708277185)
=> Show example of function message

README.md
Hi team, 
I found a typo while using your lib. (__)
Thanks :)
=> chore: Fix typo in README.md 

README.md, src/ValidationError.ts, src/schema.ts, src/types.ts, src/util/createValidation.ts
This reverts commit ee1b7317b0a9fc0e16a7d33064c3e5584bd7f2d5.
=> Revert "fix: performance improvement (#2043) (#2044)"

src/index.ts
Related to #1954 and #1906 ([comment](https://github.com/jquense/yup/issues/1906#issuecomment-1692972416)).
=> Export Lazy and Reference types

README.md
Fixed some typos in README + updated the CustomizingErrors documentation based on current code
=> fix(readme): some typos and update CustomizingErrors doc
