jquense/yup

src/util/set.js
test/mixed.js
test/yup.js

see issue #27
changes:
- added tests for the BadSet class
- reimplemented the BadSet class using an object as the underlying data structure
- changed one existing test to account for different sort order of the new implementation
notes:
- see http://jsperf.com/badset/9 for performance comparison
- the iteration order of an object is undefined in the js spec, so not all browsers do the same. thus, we can no longer rely on BadSet.prototype.values() returning the values sorted by insertion order. in my opinion this is a small price to pay for the huge speed advantage of using an object instead of an array. however, if need be i can modify this implementation to store insertion order and sort the return value of BadSet.prototype.values() before returning it. however, this comes with a …

faster implementation of the BadSet class, tests for the BadSet class

---

README.md
lib/mixed.js
src/mixed.js
test/mixed.js

I don't know what else removing that check does, I guess there was a reason for it to be there :D wdyt

allow oneOf required validation

---

src/util/isodate.js
test/date.js

This fixes an issue where a leading-zero millisecond ISO string would get parsed incorrectly.
Input: `2016-08-10T11:32:19.012Z`
Parsed as: `2016-08-10T11:32:19.120Z`

Fix incorrect leading-zero millisecond conversion

---

README.md

`mixed#validate`'s `abortEarly` option defaults to `true`, not `false`: https://github.com/jquense/yup/blob/master/src/mixed.js#L41. This took me some time to realize because the readme documents otherwise. This PR corrects that mistake!
Thanks for the great library!

Update readme to reflect abortEarly default value

---

src/ValidationError.js
src/mixed.js
test/ValidationError.js
test/array.js
test/date.js

Fixed an issue where when using yup in the following way 
```js
yup.number().min(0, 'This field must be greater than or equal to ${min}')
```
The string replace method would interpret `0` as `false` in the string replace methods `or` statement and therefore replace with an empty string.
Added some basic test cases for `ValidationError.js` `formatError` method including one checking specifically for this `0` case.
Also fixed up a few more linter issues.

Fix string interpolation 0 issue

---

README.md

Just a small update to the docs. I noticed in the [changelog](https://github.com/jquense/yup/blob/master/CHANGELOG.md#090):
> test functions are no longer passed path and context as arguments, Instead they are now values on this inside the test function.
This PR removes an outdated reference to these parameters in the README.

docs: remove outdated parameters passed to test() function

---

lib/util/clone.js
src/util/clone.js

We get the error `Can not read property 'get' of undefined`, which occurs when `getOwnPropertyDescriptor` returns `undefined`.
A similar error was [fixed](https://github.com/hapijs/hoek/commit/14113f7bc17a5850588624e8b8157df60ebc6617) in the module `hoek`.

dont fail when getOwnPropertyDescriptor returns undefined

---

src/locale.js

The word "of" was missing from the `oneOf` and `notOneOf` messages.

Fix oneOf & notOneOf messages.

---

src/locale.js

The code already uses `mixed.required` wherever a required check is
done. To reduce confusion the unused translations should be removed.

Remove unused `required` locale strings

---

README.md
src/customLocale.js
src/locale.js
test/customLocale.js

Previously, import order was important to use setLocale.
It had to import `setLocale` first, then run setLocale and import `yup`.
this pull request can set the locale via setLocale regardless of the import order.
This is also convenient when someone use it, and is also useful if someone need to load and set the user language asynchronously.

Support for setLocale regardless of import order

---

src/locale.js
src/number.js
test/number.js

Add few new methods for number. This useful use for validate ranges:
```
var yup = require('yup')
var schema = yup.object({
start: yup.number(),
end: yup.number().more(yup.ref('start'), 'End must be greater than the start')
})
schema.validate({
start: 3,
end: 5,
})
```
Tnx @maullerz for help

[added] number methods less, more, notEqual

---

README.md
src/mixed.js
test/mixed.js

Added `notRequired` method so the field can be set as not required.
I have a big form on my project and there are fields that are shown if other fields are equal to something. Applying `.required()` to everyting and then using `.notRequired()` in `.when()` method would be simpler than checking if field depends on other field and if so using different `mixed()` types in `.when()` sections.
For example, I have to use:
```javascript
yup.mixed().when('some-field', {
is: true,
then: yup.mixed().required(),  
otherwise: yup.mixed(),  
});
```
Instead of:
```javascript
const mixedType = yup.mixed().required();
mixedType.when('some-field', {
is: true,
then: mixedType,
otherwise: mixedType.notRequired(),
});
```
Keep in mind that `mixedType` can be a lot more complicated and creating a new type …

Added notRequired method to mixed type

---

package.json
yarn.lock

This resolves an issue with uglify where the toposort.array method gets removed from the compressed file.

Upgrade toposort dependency

---

package.json
yarn.lock

Fixes #214 
This should probably be treated as a short term fix - a better solution might be to revise the publish/build configuration to it inserting the `require('@babel/runtime...')` call - might be related to `runtime: false` on [this line](https://github.com/jquense/yup/blob/049e39ffe799654c6325b53c312560262ddd6ad6/rollup.config.js#L11)? You probably have a better sense of what you want to do with your published build.

add babel/runtime dependency

---

src/string.js

In code below, error messag to be a empty object `{}`.
```js
const schema = string().matches(/(hi|bye)/);
// default message is expected in message
schema
.validate('nope')
.catch(err => console.log(err));
```

fix string.matches to throw error with correct message if second arg is omitted

---

src/locale.js
src/number.js
test/number.js

Validations `lessThan` and `moreThan` use locale keys `less` and `more`. It seems these two are the only ones which use different naming for a method and locale key. It leads to an error with a `d.ts` file if you want to set up a custom locale. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L253
I think it makes more sense to change the naming of locale keys rather than changing types definition.

Rename locale keys "less" and "more"

---

package.json

Yup pulls in the latest beta version of the Babel libraries, which sometimes break because they are in Beta. If beta libraries are required, they should be pinned to specific known-good versions. This PR does that.
Addresses the recurring issue here: https://github.com/jquense/yup/issues/216#issuecomment-411033919

Pin beta packages to specific versions

---

src/array.js
src/date.js
src/object.js
test/object.js

The current implementation of `cast` always returns a new instance of object/array/date value. It creates some problems when we want to know whether or not a value was really cast.

fix: cast returns the origin value if there is nothing to cast

---

test/lazy.js

Docs don't mention that `lazy` validator is actually called with `context` as a second argument. I've covered this feature with tests and going to make another PR with updated documentation for this validator.

Lazy validator tests

---

src/object.js
test/object.js

This is the small fix for #342: cast() returns new value even if nothing has changed, but scheme has a stripped field.

fix: cast() does not work well if scheme has stripped field.

---

src/object.js
test/object.js

Commented change on #409 to dont break Promise.all chain

fix: validate() does not work with ref and abortEarly false. (#409)

---

README.md

Fixed message interpolation params description for `number.moreThan` and `number.lessThan` in README.

README moreThan and lessThan message interpolation params

---

README.md

Looks like `mixed.cast` accepts additional parameters that aren't documented.

Update `mixed.cast` documentation

---

README.md

The [documentation](https://github.com/jquense/yup#mixednullableisnullable-boolean--false-schema) for `mixed.nullable()` shows the typing as:
```
mixed.nullable(isNullable: boolean = false): Schema
```
This would imply that calling `yup.nullable()` sets the schema as **not** nullable. But in fact it does the opposite and sets the schema as nullable. Looking at [the implementation](https://github.com/jquense/yup/blob/master/src/mixed.js#L320), this is true:
```javascript
nullable(value) {
var next = this.clone();
next._nullable = value === false ? false : true;
return next;
},
```
If the argument `value` is not provided, it will be `undefined`. That will not match `false`, so `next._nullable` will be set to `true`. So a more proper documented default value is `true`.

Update README w/ proper default for nullable

---

README.md

Solves [PR #418](https://github.com/jquense/yup/issues/418) by documenting the `yup.string().length()` method in the README. I also noticed a few misuses of `a` and `an` and cleaned those up.

Document .string().length() method

---

README.md

Related to [Issue #418](https://github.com/jquense/yup/issues/418). You have already merged a PR that adds the documentation for the method. I then realized that I had not added the link that the top of the README to scroll the user down to the documentation. Sorry about that!

Update string().length() method

---

src/object.js
test/object.js

Right now `noUnknown()` changes `_options.stripUnknown` only when `noAllow` is true. So when `noAllow` is `false` in override the option still remains `true`.

fix: noUnknown() overriding

---

src/Condition.js
src/Reference.js
src/mixed.js
src/util/createValidation.js
src/util/sortFields.js
test/mixed.js

`key` cannot be a function since [`validateName`](https://github.com/jquense/yup/blob/d02ff5e59e004b4c5189d1b9fc0055cff45c61df/src/Reference.js#L3) ensures that it is a string.
`isSelf` is not used anywhere and `key="."` isn't supported by `property-expr` getter.
For working self references i opened [pull request](https://github.com/jquense/expr/pull/9) in `property-expr` to support empty string path. (currently `getter("")` works, but `getter("", true)` which is used in Reference.js throws)

feat: support self references

---

src/mixed.js
src/object.js

Number 8 from #454 
```js
number().optional(); // reads better and present in joi, same with unknown().
```

feat: aliases `optional()` and `unknown()`

---

src/mixed.js

Number 6 from #454
```js
mixed().strict().strict(false); // not strict anymore
```

feat: allow undo strict()

---

src/mixed.js
test/mixed.js

Number 3 from #454
```js
mixed().withMutation(schema => {
schema.withMutation(changeA);
changeB(schema);
}); // now changeB gets mutable instance
```

feat: allow withMutation() nesting

---

README.md

Remove some inconsistencies in readme js snippets.
Most changes:
- let or const to var
- `inst` to `schema`
- \`\`\`javascript to \`\`\`js
- // -> or //=> to // =>
- await for async calls
- space after comment and first letter is small
- blank line between schema creation and usage
- bool() to boolean()

fix: remove README js inconsistencies

---

src/array.js
src/mixed.js
src/string.js
test/mixed.js

Number 1 from #454
Removed redefinition of `required()` from `array` and `string`, instead added `_isFilled(value)` method for subtypes to override. Redefinition of `required()` causes problems with `concat`:
```js
mixed().required().concat(array()).isValidSync([]); // now false, not true
```

fix: concat of required() for array/string

---

src/Condition.js
src/Lazy.js
src/mixed.js
src/util/reach.js
test/mixed.js
test/object.js
test/yup.js

This PR allows safely nest `lazy`s and `when`s in themselves and each other. (Asked in #335 for example)
Currently there is a difference between calling `resolve()` on `lazy` and on `mixed` with `when`s:
- `lazy.resolve()` will return a schema not connected to `lazy` instance. So calling `resolve()` on a returned schema does not call `lazy` body anymore.
- `mixed.resolve()` will return a schema resulted by `concat`ing base schema and conditional one, as nor `mixed.concat()` nor `mixed.resolve()` remove initial `when` conditions they are present in resulted schema and those conditions get called and merge their results on subsequent `resolve` calls of merged schema.
So, in a second case it is not a final resolve, but a partial one (resulted schema will contain conditions). For most cases …

feat: finalize resolve()

---

src/mixed.js
test/mixed.js

Two things:
1) Fix. If you use `test()` with multiply arguments like `test('name', func)` then you will be provided with default message (`locale.default`). But not if you use it with `opts` object without message `test(opts)` or with second argument as `undefined` `test('name', undefined, func)` (it is assumed right now that since there are 3 arguments then message is present). Now all variants treated equally and if message is `undefined` then it will be set to `locale.default`.
2) Small feature. Now it is possible to write `test(func)`. Since `name` is needed only for exclusive tests it can be omitted (like it is possible to omit it in `opts` form).

fix: default message for test with object

---

src/number.js
test/number.js

This works correctly for large numbers.
Related to https://github.com/jquense/yup/pull/147

Replace integer check with Number.isInteger

---

src/string.js

I noticed that `string.email()` and `string.url()` don't have associated test function names and appear as `undefined` in the `tests` array of `SchemaDescription`. 
This just makes sure that a proper name is sent through the `matches` function.

Add function test names to email and url

---

src/object.js
test/object.js

This fixes #536 by switching to the `foo.bar["baz"]` syntax if the key contains a dot.
Alternatively, that syntax could be used unconditionally; I chose not to so as to keep the path pretty when possible.
There are, of course, other characters that would break the path syntax, e.g. square brackets and quotes.  The current approach would work for anything but double quotes; I'm not familiar enough with lodash's path syntax to come up with something that would always work.

Use the alternate object index path syntax if the key contains dots

---

README.md

Show how to use Yup with TypeScript and how to use the `InferType` to create a type alias from a Yup schema.

docs: Add usage from TypeScript

---

README.md

Added an example of using `yup.mixed<T>()` to use custom type definitions with TypeScript.

Example of custom type defuntion with mixed()

---

src/object.js
test/helpers.js
test/mixed.js
test/object.js

This PR fixes an issue where using `when` on an object with dependencies on properties that were not specified in the schema, caused the validation to become asynchronous even with `sync` set to true.

fix: synchronous conditional object validation with unknown dependencies

---

README.md

Fixes https://github.com/jquense/yup/issues/644
This will include in the readme an example of how to customize messages using functions, which is especially useful for projects with i18n.

Add setLocale example with functions

---

src/date.js

Hopefully this fixes #234 and doesn't introduce any new buggy conditions.
I have modified return `value ? new Date(value) : invalidDate;` to `return value > -1 ? new Date(value) : invalidDate;` keeping in mind any valid values will be greater than -1, (i.e 0 or above) and the invalid value like `NaN` doesn't satisfy `> -1` condition.

fix: unix epoc bug in date parser

---

src/array.js
test/array.js

At the moment during casting process Array type passes the field path to sub items without resolving it according to sub item array index.
The path is exposed to end consumer as part of context in conditional validation `when` (could be somewhere else).
If conditional validation relies on context path - this behaviour will lead to bugs.

Fix array path resolve for descendants

---

README.md

Addresses #708. Will open a PR in DefinitelyTyped to fix the TS definition of `createError`.

Document optional params property in createError

---

README.md

Mention that `undefined` does not fail the `oneOf` validator.

Mention the special role of `undefined` in `mixed.oneOf`

---

.babelrc
.gitignore
package.json

Related to #311.
I see that there is a `rollup.config.js` that isn't hooked up yet. I guess that's probably the better way to go long term since people want a UMD build too (#100).
I did experiment and got Babel to output UMD too with another `.babelrc` entry for `"modules": "umd"` but it was multiple files so I'm not sure if that's what's wanted for UMD? I don't use UMD myself so I have no idea.

Add ESM build

---

README.md
src/locale.js
src/mixed.js
test/mixed.js

After seeing this comment https://github.com/jquense/yup/issues/153#issuecomment-349679982 in an issue about the error when mixing `required` with `nullable` I thought it would be nice to have this validation.

feat: Add defined() validation to mix

---

src/locale.js
src/object.js
test/object.js

Currently `noUnknown` does not provide the list of unknown key, which makes it very hard to debug. This PR fixes it.

feat: provide keys in default noUnknown message

---

src/string.js

Came across issue #849 this morning. Hopefully this closes #849

Allow passing of function to .matches() options/message param

---

src/object.js
test/object.js

Closes #857 
This PR fix a bug when `strict` is used on nested objects and the cast still happens

Bug: fix object bug when nested object has a property with strict

---

CHANGELOG.md
README.md
package.json

Note: This is a draft PR because it should not be merged until DefinitelyTyped/DefinitelyTyped#44589 is merged.
- Removes the "Why does InferType not default to nonRequired()" since this is incorrect due to DefinitelyTyped/DefinitelyTyped#44589
- Adds `defined` calls to the `firstName` and `nickName` in the example
- Updates example and adds note for using `oneOf`` without using the generic type parameter of `mixed` (DefinitelyTyped/DefinitelyTyped#44573)
- Adds an example for how you might ensure that a schema conforms to an interface or type
**Note**: Does not change the version in package.json.

Update readme to account for changes in types and add additional example

---

src/array.js
src/mixed.js
src/object.js
test/mixed.js

I made a terrible attempt at this PR earlier. This should do it.
This resolves #551 and adds the capability to help with #553.

Allow access to parent schema (and unlimited ancestors!) in test context

---

README.md
src/locale.js
src/string.js
test/string.js

* Adds a new validation method to **String** schemas.
* This new method allows UUID validation via a regex.
* Empty strings are not allowed since they are not a valid UUID.
The regex used to validate an UUID was taken from the project [uuidv4](https://www.npmjs.com/package/uuidv4).
`/^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i`
For the test cases valid UUIDs were generated using [uuidv4](https://www.npmjs.com/package/uuidv4).

String UUID validation via a regex

---

src/array.js
test/array.js

Superseeds #949; Fixes #676
Yup validation no longer throws on sparse arrays:
```javascript
let schema = y.array(number())
let arr = []
arr[1] = 1
arr
// => [empty, 1]
// fixes TypeError: Cannot read property 'fulfilled' of undefined
schema.validate(arr, {
abortEarly: false,
context: {},
})
```
---
Yup required validation now treats empty slots in sparse arrays as missing:
```javascript
let schema = y.array(y.number().required())
let arr = []
arr[1] = 1
arr
// => [empty, 1]
await schema.isValid(arr) // false
await schema.compact().isValid(arr) // true
```
---
Yup preserves empty slots in sparse arrays when valid:
```javascript
let schema = y.array(y.number())
let arr = []
arr[1] = 1
arr
// => [empty, 1]
let value = await schema.validate(arr)
0 in value 
// => false
```

Handle sparse array positions as undefined V2

---

package.json
yarn.lock

Fixes vulnerability issue described in https://github.com/jquense/yup/issues/1046.

Upgrades property-expr dependency to 2.0.4

---

src/mixed.js

Moving `_whitelist` and `_blacklist` initializations inside `proto` fixes: `createSetIterator called on incompatible receiver` error in IE11

fix: IE11 clone()

---

README.md

While it may seem obvious to many, I've previously found myself searching the docs more than once for
whether or not I wanted to return `true` or `false` in `mixed.test` validators. This is a minor change to
the README that clarifies the return value.
Cleaned up some long lines and capitalized the beginning of each paragraph

docs: Clarify return value of mixed.test

---

package.json
src/locale.js
test/object.js
test/setLocale.js

https://huntr.dev/users/ljharb has fixed the Prototype Pollution vulnerability 🔨. ljharb has been awarded $25 for fixing the vulnerability through the huntr bug bounty program 💵. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/yup/pull/2
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/yup/1/README.md
This uses a null object as the base locale data, so it doesn't *have* a prototype to pollute.
Prototype Pollution refers to the ability to inject properties into existing JavaScript language construct prototypes, such as objects.
JavaScript allows all Object attributes to be altered, including their magical attributes such as proto, …

Security Fix for Prototype Pollution - huntr.dev

---

src/string.js

Change in uuid regexp to more exactly meet the specs defined in RFC 4122. The regexp matches the string with the following the format: xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx where x is one of [0-9, a-f] M is one of [1-5], and N is [8, 9, a, or b] and 00000000-0000-0000-0000-000000000000 is the zero value.

Change uuid's regexp

---

src/boolean.js
src/locale.js
test/bool.js

This resolves https://github.com/jquense/yup/issues/904 :)

add `isTrue` and `isFalse` checks on boolean

---

src/Lazy.ts

Add missing functions to Lazy:
isValid
isValidSync
isType
These are all validation functions that have a value parameter, so it makes sense for Lazy to wrap them.

Add additional functions to Lazy class

---

src/string.ts

The second parameter to matches() should be optional.

Make StringSchema.matches options optional

---

src/index.ts

1. Move array before object so that inference works correctly
1. Include `Lazy` as part of `ArraySchema`'s generic, to match the class definition
Here's a quick snippet that illustrates why 1 is necessary:
```typescript
export const array: Array<string> = ["abc"];
// Valid - an Array is a Record (note: AnyObject is a type alias for Record<string, any>)
export const record: Record<string, any> = array;
// Doesn't compile
export const anotherArray: Array<string> = record;
```
By the way, I noticed that eslint isn't checking the `$ExpectType` comments in `test/type.ts`... I investigated it for a little bit, but ran into more problems so I gave up. You need to add `--ext=.ts,.js` when running eslint to make sure it checks the ts file, but then eslint started to give parser errors and I lost …

Fix array handling in SchemaOf type

---

src/schema.ts
test/mixed.js

Otherwise spreading spec values like previously would overwrite the base schema spec values with undefined.
Closes #1160.

Do not initialize spec values with undefined

---

package.json

upgraded lodash-es min version from 4.17.11 to 4.17.15 due to security vulnerabilty found by Checkmarx
ran npm run test...all passed

upgraded lodash-es min version from 4.17.11 to 4.17.15

---

src/util/reach.ts

makes the last 2 arguments of the reach utility function (and getIn) optional 
closes #1180

reach and getIn make last 2 arguments optional

---

src/Reference.ts

The `create()` method in `Reference.ts` was missing the generic, which caused a type error in the following example
```typescript
yup
.object({
availableFrom: yup.number(),
availableTo: yup
.number()
.moreThan(yup.ref('availableFrom')),
});
```
Error:
```
Argument of type 'Reference<unknown>' is not assignable to parameter of type 'number | Reference<number>'.
```
In this PR I add a generic to the `create()` method and type `Reference` and `ReferenceOptions` with it.

Add generic to Reference.create()

---

src/index.ts

Follow up to #1169, because in my haste to rebase I overlooked adding `Lazy` to the `ArraySchema` generic in `ObjectSchemaOf`. I also simplified the `ObjectSchemaOf` definition since it doesn't need to repeat the `SchemaOf` definition. I also fixed my incorrect formatting from #1169.
I've tested this against my own project via `yarn link` so I know it at least works for my use cases.

Fix ObjectSchemaOf type definition

---

src/mixed.ts

Fixes ts error `Exported variable 'Schema' has or is using name 'MixedSchema' from external module "x/node_modules/yup/lib/mixed" but cannot be named.` with --declarations builds.
The MixedSchema class needs to be exported so it can be used in declaration files.

Export MixedSchema to fix ts with --declarations

---

src/schema.ts

fixed rollup build 
```
error during build:
Error: 'Config' is not exported by node_modules/yup/es/util/types.js, imported by node_modules/yup/es/schema.js
```

use type import/export

---

src/array.ts
test/types.ts

This merge request is supposed to fix #1253 
We at Opplane <https://opplane.com/> use `yup` on both `frontend` and backend for some of our projects for it's type-safety while keeping it simple.

Array required() and defined() will no longer return any

---

src/index.ts
test/types.ts

Resolve #1243 and #1302.
Add a test for SchemaOf containing Date objects
and an array of date objects.

Fix SchemaOf<>'s treatment of Date objects.

---

src/util/createValidation.ts
test/mixed.js

Fixes https://github.com/jquense/yup/issues/1326

fix: prevent unhandled Promise rejection when returning rejected Promise inside test function

---

src/util/isAbsent.ts
src/util/isSchema.ts

There's ESLint rules that warn on exporting an anonymous arrow function (See #1161) 
While I agree this does not break anything, it seems like a very small fix that does not impact yup and fixes a lot of console spam coming from NextJS (and maybe other projects that check for anonymous functions with fast refresh).

fix(utils): use named functions for default exports

---

package.json
yarn.lock

4.17.20 is flagged as being vulnerable to:
- CVE-2021-23337 Lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function.
- CVE-2020-28500 Lodash versions prior to 4.17.21 are vulnerable to Regular Expression Denial of Service (ReDoS) via the toNumber, trim and trimEnd functions.
See - https://www.openhub.net/p/lodash/security?filter%5Bmajor_version%5D=&filter%5Bperiod%5D=1&filter%5Bversion%5D=3409002148&filter%5Bseverity%5D=
Bumping to 4.17.21 for both lodash and lodash-es.
Previously the pinned versions for both drifted as the Lodash project had not been releasing lodash-es at the same time as lodash. They have resolved the release problems on their side and both are again released in sync.

update lodash/lodash-es to fix CVEs flagged in 4.17.20

---

src/index.ts
test/types.ts

Similar to  #1305, this allows the user to implement their own types for classes and not have fields forced to be of type ObjectSchema. This is very helpful when wanting to extend yup for ` js-joda LocalTime` for example.
This is backwards compatible as the new generic type `CustomTypes` is not mandatory and is defaulted to never.

Allows custom types to be passed to avoid cast to ObjectSchema

---

README.md

I would like to suggest a change in the README removing two words to lighter terms.

docs(README): update block and allow terminology

---

src/util/createValidation.ts

`originalValue` is listed as a valid property on `testContext` [per the docs](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema), and also exists on [the community types for yup](https://github.com/abnersajr/DefinitelyTyped/blob/a186d99d0c3a92424691a82130374a1b9145c7cd/types/yup/index.d.ts#L446), but it is missing in the official types.
Fixes #1335

Add originalValue to TestContext type

---

README.md

[README.md](https://github.com/jquense/yup/#mixedstrictisstrict-boolean--false-schema) lists the default value of the `isStrict` argument of the `mixed.strict` function as `false`.
However, [schema.ts](https://github.com/jquense/yup/blob/master/src/schema.ts#L503) shows that the value used here is actually `true`. The documentation should be updated accordingly.

Fix documentation of mixed.strict

---

README.md
src/Condition.ts
src/schema.ts
test/array.ts
test/mixed.ts
test/object.ts
test/types/types.ts
test/yup.js

BREAKING CHANGE: The function version of `when()` has been changed to make it easier to type. values are always passed as an array and schema, and options always the second and third argument. `this` is no longer set to the schema instance.  and all functions _must_ return a schema to be type safe
```diff
string()
-   .when('other', function (other) => {
-      if (other) return this.required()
+   .when('other', ([other], schema) => {
+     return other ? schema.required() : schema
})
```

feat: stricter `when` types and API

---

README.md
docs/typescript.md
src/mixed.ts
src/object.ts
src/util/objectTypes.ts
test/types/types.ts

BREAKING CHANGE: concat works shallowly now. Previously concat functioned like a deep merge for object, which produced confusing behavior with incompatible concat'ed schema. Now `concat` for objects works similar to how it works for other types, the provided schema is applied on top of the existing schema, producing a new schema that is the same as calling each builder method in order

feat: concat() is shallow and does not merge

---

README.md
docs/extending.md
src/Lazy.ts
src/array.ts
src/boolean.ts
src/date.ts
src/index.ts
src/mixed.ts
src/number.ts
src/object.ts
src/schema.ts
src/string.ts
test-setup.js
test/yup.js

BREAKING CHANGE: `mixed` schema are no longer treated as the base class for other schema types. It hasn't been for a while, but we've done some nasty prototype slinging to make it behave like it was. Now typescript types should be 1 to 1 with the actual classes yup exposes. 
In general this should not affect anything unless you are extending (via `addMethod` or otherwise) `mixed` prototype. 
```diff
import {
-  mixed,
+  Schema,
} from 'yup';
- addMethod(mixed, 'method', impl)
+ addMethod(Schema, 'method', impl)
```

feat: simplify base class hierarchy

---

README.md

In the example provided in the Getting Started section of the README:
> The `string` import was duplicated by mistake
>The `number` import was missing

fix: typo README#Getting-Started duplicated import

---

README.md

This PR changes the README file. It fixes the typo "coarce" to "coerce".

fix(docs): correct typo "coarce" to "coerce"

---

README.md

are passed also passed -> are also passed

Fix Typo : delete duplicate word "passed"

---

src/Lazy.ts
src/index.ts
src/object.ts
src/setLocale.ts
test/object.ts
test/types/types.ts

BREAKING CHANGE: The types for Lazy have changes a bit, it's unlikely that this affects anyone but it is technically a breaking change.
this also fixes: #1144

feat: better Lazy types and deepPartial fixes

---

src/Lazy.ts
src/schema.ts
src/types.ts
test/mixed.ts
test/types/types.ts

Adds a `cast` option to not throw on optionality mismatches after casting. This is being added to support migration from pre-v1 where cases like `string().nullable().required()` are supported. This case is generally used to handle parsing server side "default" values to feed into a form. Initial values may be null or missing but require filling in by a user before submitting the value back to server. 
Going forward the approved way to handle these cases is with multiple schema using conditional when's to set `nullable` or using `schema.deepPartial()` to create an optional version of itself.

feat: add cast nullability migration path.

---

src/schema.ts
src/util/ReferenceSet.ts
test/mixed.ts
test/types/types.ts

closes: #768 #104
BREAKING CHANGE: previously `oneOf` required adding `null` explicitly to allowed values when using oneOf. Folks have found this confusing and unintuitive so I am deferring and adjusting the behavior

feat: respect nullable() with oneOf

---

README.md

Was reading through the docs and noticed a typo, and took the opportunity to see if there was any more to fix up!

fix: correct minor typos in README

---

src/string.ts
test/string.ts

In a project, we need to undo some `.required()` fields in `.when()`-conditions, but for `string()` that does not work 🙈.
This should fix it. 🤞 
Thank you for your work maintaining this validation library (coming here from the Formik-recommendation). 💚

fix: string().notRequired()

---

README.md
src/schema.ts
test/mixed.ts

This PR addresses https://github.com/jquense/yup/issues/1886.
The `describe()` method now returns the result of `schema.getDefault()`. I am currently updating a library that converts Yup schemas to JSONSchemas. The new `optional` and `nullable` flags have been helpful. The addition of the `default` would be super helpful as well.
Let me know if you have any questions.

Add getDefault results to the describe method

---

CHANGELOG.md
README.md

Can you also edit [1906](https://github.com/jquense/yup/issues/1906) and add a link to [1579](https://github.com/jquense/yup/issues/1579) in the "Stricter when API" section?

Improve docs on migrating to 1.0.0

---

src/object.ts
src/schema.ts
test/object.ts

Pass context to nested elements for both `getDefault` and `cast` That solves the issue where conditional defaults of nested elements were not resolving correctly if they had context dependency
Added tests are covering examples of use cases that are being fixed

Respect context for object's children

---

README.md

fixes: https://github.com/jquense/yup/issues/1978

fix(docs): Broken anchores

---

README.md
src/date.ts
src/number.ts
src/object.ts
src/schema.ts
test/date.ts
test/number.ts
test/object.ts

Previously, schema that parse to invalid values like `InvalidDate` or `NaN` always tripped the `typeError` validation before the nullability error. This was the due to typeError no longer firing on `null` values, with the expectation that it would always hit the newer nullability check. 
This change fixes the issue for Number and Date schema, so that they act the same as String and other schema, where `null` values do not trigger the typeError validation. The consequence of this is that casting `null` values for non-nullable number schema, now return `null` instead of `NaN` and dates, return `null` instead of `InvalidDate`. Essentially these schema will not fruitlessly attempt to coerce `null` into a number or date anymore. 
I am marking this as a bug fix since it is, and as with most bug …

Potentially breaking: Make null validation errors consistent across schema

---

src/index.ts

Export this `printValue` function in the bundle in order to allow translation packages that uses this function to work properly.

feat: expose printValue (#2002)

---

README.md
src/index.ts
src/schema.ts

Resolves https://github.com/jquense/yup/issues/2018.
Allows schema metadata to be strongly typed through declaration merging. From the updated `README.md`:
> A custom `SchemaMetadata` interface can be defined through
> [merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces)
> with the `CustomSchemaMetadata` interface. Start by creating a `yup.d.ts` file
> in your package and creating your desired `CustomSchemaMetadata` interface:
> 
> ```ts
> // yup.d.ts
> import 'yup';
> declare module 'yup' {
>   // Define your desired `SchemaMetadata` interface by merging the
>   // `CustomSchemaMetadata` interface.
>   export interface CustomSchemaMetadata {
>     placeholderText?: string
>     tooltipText?: string
>     // …
>   }
> }
> ```

feat: Allow schema metadata to be strongly typed

---

src/util/createValidation.ts

Handle sync validations

---

README.md
package.json
src/ValidationError.ts
src/schema.ts
src/types.ts
src/util/createValidation.ts

Resolves performance issues for large data validation described on #2043 :
- Arrays of ValidationError
- Mutate the array with splice instead of using concat
- ValidationError class
- Add the new option "disableStackTrace" to stop capturing stack trace when instantiating ValidationError
- Stop ValidationError extending Error, so no need to call super() when instantiating ValidationError

fix: performance improvement (#2043)

---

src/locale.ts

Currently it's impossible to use custom locale for tuples

fix: add tuple to locale object

---

src/array.ts
src/object.ts
src/tuple.ts
test/mixed.ts

Solves: https://github.com/jquense/yup/issues/2050
This PR updates the `object`, `array`, and `tuple` schemas such that they are resolved before being described. This ensures that the `describe` method works for things like `object({...}).when(...)`

Allow parent resolve before describe.

---

README.md
src/array.ts
src/date.ts
src/mixed.ts
src/number.ts
src/object.ts
src/string.ts
src/tuple.ts

Fixes https://github.com/jquense/yup/issues/2069
Adds an optional `msg?: Message` argument to `nonNullable` method on every schema object. The argument is already supported by the [base Schema class](https://github.com/jquense/yup/blob/master/src/schema.ts#L713), and we only need to pass it properly with TypeScript.
Also updates `nullable` and `nonNullable` signatures in `README.md`.

fix: add optional message to nonNullable schema methods

---

README.md

I noticed let and const are used interchangeably in README. For consistency, I'd like to propose to use either/or. The previous PR https://github.com/jquense/yup/pull/2226 was about changing all `let`s to `const`s

let/const consistency in README: let preference

---

src/ValidationError.ts
src/index.ts
src/types.ts

- `ValidationError.formatError()` overwrites `path` with a more friendly `label` string (if defined) for more friendly error message interpolation; however, this causes the `path` data to be lost entirely.
- Rather than undertake refactoring this logic and cause a breaking change, where using alternative values for interpolating `${path}` within error strings should arguably be a concern that's left to the `message` function, I opted to simply create a new `params` property—`originalPath`—for recording this value.
- Update `MessageParams` type with `originalPath: string;` property
- Add `MessageParams` and `AnyMessageParams` to library exports
- I couldn't see a reason why these types are private, and I'd certainly love to make use of them.

Fix `ValidationError.formatError()` clobbering `path` param

---

README.md
package.json
src/Lazy.ts
src/schema.ts
src/standardSchema.ts
test/standardSchema.ts
yarn.lock

This is a PR that implements the [standard schema interface](https://github.com/standard-schema/standard-schema) for yup.
**Motivation:** Standard schema is an initiative that is aimed to get all Typed schema providers to support a unified interface that will enable various tools and 3rd party libraries to seamlessly integrate with "a schema provider" which reduces friction when migrating from one provider to the other, and allows mixing these providers if one is suited for a task more than the rest. Another benefit is it allows 3rd party authors to ditch the "resolver" pattern which in turn reduces their users' friction.
We discussed this briefly in #2255 with no clear green light given on this, so I understand if this is something you don't want the burden of maintaining. I already did …

feat: Implement standard schema interface
